; generated by goldly on 2023-08-15 11:41:09
(ns goldly-bindings-generated
  (:require [webly.build.lazy :refer-macros [wrap-lazy]]
            [pinkie.error]
            [pinkie.text]
            [pinkie.html]
            [pinkie.jsrender]
            [pinkie.throw-exception]
            [pinkie.default-setup]
            [pinkie.pinkie]
            [goldly.page.no-page]
            [goldly.sci.error]
            [goldly.sci.eventhandler]
            [frontend.settings.local-storage]
            [pinkgorilla.repl.cljs.webly]
            [re-frame.core]
            [pinkgorilla.repl.cljs.load]
            [frontend.routes]
            [frontend.routes.events]
            [frontend.page]
            [frontend.page.viewer]
            [goldly.page.page]
            [clojure.walk]
            [pinkgorilla.repl.cljs.jsloader]
            [pinkgorilla.repl.cljs.component]
            [applied-science.js-interop]
            [pinkgorilla.repl.cljs.js-interop]
            [sci.configs.applied-science.js-interop]
            [clojure.edn]
            [reval.default]
            [reval.type.converter]
            [reval.editor]
            [reagent.core]
            [sci.configs.reagent.reagent]
            [goog.object]
            [clojure.string]
            [modular.ws.core]
            [pinkgorilla.repl.cljs.format]
            [goog.string.format]
            [goog.string]
            [ui.highlightjs]
            [modular.oauth2.token.ui]
            [modular.oauth2.user.view]
            [pinkgorilla.debounce]
            [goldly.service.core]
            [viz.hiccup]
            [viz.show]
            [sci.configs.funcool.promesa]))
(def compile-time "2023-08-15 11:41:09")
(def bindings-generated {'debounce pinkgorilla.debounce/debounce})
(def ns-generated
  {'promesa.core sci.configs.funcool.promesa/promesa-namespace,
   'ajax.core {'GET pinkgorilla.repl.cljs.load/http-get},
   'viz.show {'show viz.show/show},
   'ws {'send! modular.ws.core/send!},
   'promesa.protocols sci.configs.funcool.promesa/promesa-protocols-namespace,
   'goldly.nav {'nav frontend.routes/goto!, 'current-route frontend.routes/current-route},
   'goldly.service.core {'run goldly.service.core/run,
                         'run-a goldly.service.core/run-a,
                         'run-a-map goldly.service.core/run-a-map,
                         'run-cb goldly.service.core/run-cb,
                         'wait-chan-result goldly.service.core/wait-chan-result},
   'container {'sidebar (wrap-lazy pinkgorilla.layout.sidebar/sidebar),
               'tab (wrap-lazy pinkgorilla.layout.tab/tab),
               'description-list (wrap-lazy pinkgorilla.layout.description-list/description-list),
               'panel (wrap-lazy pinkgorilla.layout.panel/panel)},
   'clojure.end {'read-string clojure.edn/read-string, 'read clojure.edn/read},
   'goldly.page {'available goldly.page.page/available-pages,
                 'show goldly.page.page/show-page,
                 'add goldly.page.page/add-page},
   'ui.debounce {'debounce pinkgorilla.debounce/debounce},
   'goldly.sci.error {'error-view goldly.sci.error/error-view, 'exception->error goldly.sci.error/exception->error},
   'ui.bidi {'start-router! frontend.routes/start-router!,
             'nav! frontend.routes/nav!,
             'goto! frontend.routes/goto!,
             'hard-redirect! frontend.routes/hard-redirect!,
             'link frontend.routes/link,
             'reagent-page frontend.page/reagent-page,
             'page-viewer frontend.page.viewer/page-viewer,
             'refresh-page frontend.page.viewer/refresh-page},
   'reagent.core sci.configs.reagent.reagent/reagent-namespace,
   'goldly.service {'run goldly.service.core/run,
                    'run-a goldly.service.core/run-a,
                    'run-cb goldly.service.core/run-cb,
                    'wait-chan-result goldly.service.core/wait-chan-result},
   'ui.highlightjs {'highlightjs ui.highlightjs/highlightjs},
   're-frame.core {'dispatch re-frame.core/dispatch,
                   'subscribe re-frame.core/subscribe,
                   'reg-event-db re-frame.core/reg-event-db,
                   'reg-event-fx re-frame.core/reg-event-fx},
   'goog.string {'format goog.string/format},
   'modular.ws.core {'send! modular.ws.core/send!},
   'js-loader {'with-js pinkgorilla.repl.cljs.jsloader/with-js,
               'browser-defined? pinkgorilla.repl.cljs.jsloader/browser-defined?,
               'load-always pinkgorilla.repl.cljs.jsloader/load-always,
               'load-js pinkgorilla.repl.cljs.jsloader/load-js,
               'component pinkgorilla.repl.cljs.component/component},
   'reagent.ratom sci.configs.reagent.reagent/reagent-ratom-namespace,
   'ui.webly {'notify pinkgorilla.repl.cljs.webly/notify, 'dialog pinkgorilla.repl.cljs.webly/dialog},
   'viz.hiccup {'resolve-hiccup viz.hiccup/resolve-hiccup},
   'localstorage {'ls-get frontend.settings.local-storage/ls-get,
                  'ls-set! frontend.settings.local-storage/ls-set!,
                  'ls-remove! frontend.settings.local-storage/ls-remove!},
   'viz {'show viz.show/show},
   'goldly {'compile-time compile-time,
            'bindings bindings-generated,
            'eventhandler goldly.sci.eventhandler/eventhandler-fn,
            'error-view goldly.sci.error/error-view,
            'exception->error goldly.sci.error/exception->error},
   'ui.pinkie {'error-boundary pinkie.error/error-boundary,
               'text pinkie.text/text,
               'html pinkie.html/html,
               'js-fun pinkie.jsrender/render-js,
               'throw-ex pinkie.throw-exception/exception-component},
   'reval.editor {'block-for reval.editor/block-for},
   'clojure.walk {'postwalk clojure.walk/postwalk,
                  'prewalk clojure.walk/prewalk,
                  'keywordize-keys clojure.walk/keywordize-keys,
                  'walk clojure.walk/walk,
                  'postwalk-replace clojure.walk/postwalk-replace,
                  'prewalk-replace clojure.walk/prewalk-replace,
                  'stringify-keys clojure.walk/stringify-keys},
   'reagent.debug sci.configs.reagent.reagent/reagent-debug-namespace,
   'applied-science.js-interop sci.configs.applied-science.js-interop/js-interop-namespace,
   'goog.object {'set goog.object/set, 'get goog.object/get},
   'clojure.string {'split clojure.string/split,
                    'join clojure.string/join,
                    'escape clojure.string/escape,
                    'blank? clojure.string/blank?,
                    'replace clojure.string/replace,
                    'lower-case clojure.string/lower-case},
   'applied-science.js-interop.goldly {'obj->clj pinkgorilla.repl.cljs.js-interop/obj->clj,
                                       'value-of pinkgorilla.repl.cljs.js-interop/value-of},
   'pinkie {'register-tag pinkie.pinkie/register-tag,
            'tags pinkie.pinkie/tags,
            'render pinkie.pinkie-render/pinkie-render},
   'modular.oauth2 {'provider-status-grid modular.oauth2.token.ui/provider-status-grid,
                    'user-login modular.oauth2.user.view/user-login},
   'reval.type.converter {'value-type->hiccup reval.type.converter/value-type->hiccup}})
(def lazy-modules
  {"cljs-pprint-frisk" {'cljs.pprint {:sci-def ['pprint 'print-table],
                                      :loadable (shadow.lazy/loadable [ui.pprint/pprint ui.pprint/print-table])},
                        'ui.frisk {:sci-def ['frisk], :loadable (shadow.lazy/loadable [ui.frisk/frisk])}},
   "tick" {'tick.core {:sci-def ['now 'time], :loadable (shadow.lazy/loadable [tick.core/now tick.core/time])},
           'tick.goldly {:sci-def ['dt-format], :loadable (shadow.lazy/loadable [pinkgorilla.repl.cljs.tick/dt-format])}},
   "ui-codemirror" {'ui.codemirror {:sci-def ['codemirror-unbound 'codemirror 'codemirror-viewonly 'codemirror-themed],
                                    :loadable (shadow.lazy/loadable
                                               [ui.codemirror.unbound.codemirror/codemirror-unbound
                                                ui.codemirror.bound.codemirror-atom/codemirror-atom
                                                ui.codemirror.bound.codemirror-atom/codemirror-atom-viewonly
                                                ui.codemirror.bound.codemirror-themed/codemirror-themed])},
                    'cm {:sci-def ['style-inline
                                   'style-fullscreen
                                   'get
                                   'focus
                                   'blur
                                   'set-code
                                   'get-code
                                   'cursor-position],
                         :loadable (shadow.lazy/loadable
                                    [ui.codemirror.unbound.theme/style-codemirror-inline
                                     ui.codemirror.unbound.theme/style-codemirror-fullscreen
                                     ui.codemirror.registry/get-editor
                                     ui.codemirror.api.focus/focus
                                     ui.codemirror.api.focus/blur
                                     ui.codemirror.api.code/set-code
                                     ui.codemirror.api.code/get-code
                                     ui.codemirror.api.position/cursor-position])}},
   "ui-repl" {'http {:sci-def ['get-str 'get-edn 'get-json 'application-url 'ws-origin],
                     :loadable (shadow.lazy/loadable
                                [pinkgorilla.repl.cljs.http/get-str
                                 pinkgorilla.repl.cljs.http/get-edn
                                 pinkgorilla.repl.cljs.http/get-json
                                 pinkgorilla.repl.cljs.http/application-url
                                 pinkgorilla.repl.cljs.http/ws-origin])},
              'goldly.js {:sci-def ['timeout 'interval 'alert 'evt-val 'parse-float 'jsx->clj 'to-fixed],
                          :loadable (shadow.lazy/loadable
                                     [pinkgorilla.repl.cljs.js/timeout
                                      pinkgorilla.repl.cljs.js/interval
                                      pinkgorilla.repl.cljs.js/alert
                                      pinkgorilla.repl.cljs.js/evt-val
                                      pinkgorilla.repl.cljs.js/parse-float
                                      pinkgorilla.repl.cljs.js/jsx->clj
                                      pinkgorilla.repl.cljs.js/to-fixed])},
              'goldly.log {:sci-def ['info 'warn 'error],
                           :loadable (shadow.lazy/loadable
                                      [pinkgorilla.repl.cljs.log/info
                                       pinkgorilla.repl.cljs.log/warn
                                       pinkgorilla.repl.cljs.log/error])}},
   "ui-input" {'input {:sci-def ['button 'progressbar 'textbox 'select 'checkbox],
                       :loadable (shadow.lazy/loadable
                                  [pinkgorilla.input.button/button
                                   pinkgorilla.input.progressbar/progressbar
                                   pinkgorilla.input.bound/text-a
                                   pinkgorilla.input.bound/select-a
                                   pinkgorilla.input.bound/checkbox-a])}},
   "ui-ionslider" {'input2 {:sci-def ['slider],
                            :loadable (shadow.lazy/loadable [pinkgorilla.input.ionslider-bound/slider-ion-a])}},
   "ui-site" {'layout {:sci-def ['header-main 'header-main-footer 'sidebar-main],
                       :loadable (shadow.lazy/loadable
                                  [ui.site.layout/header-main
                                   ui.site.layout/header-main-footer
                                   ui.site.layout/sidebar-main])},
              'site {:sci-def ['people
                               'message-button
                               'ipsum
                               'bullet-points
                               'footer
                               'splash-message
                               'foto-right
                               'fotos-with-text
                               'header-menu
                               'foto-left
                               'foto-bottom
                               'cols-three],
                     :loadable (shadow.lazy/loadable
                                [ui.site.template/people
                                 ui.site.template/message-button
                                 ui.site.ipsum/ipsum
                                 ui.site.template/bullet-points
                                 ui.site.template/footer
                                 ui.site.template/splash-message
                                 ui.site.template/foto-right
                                 ui.site.template/fotos-with-text
                                 ui.site.template/header-menu
                                 ui.site.template/foto-left
                                 ui.site.template/foto-bottom
                                 ui.site.template/cols-three])}},
   "ui-spaces" {'spaces {:sci-def ['bottom
                                   'left-resizeable
                                   'description
                                   'fill
                                   'right
                                   'viewport
                                   'top
                                   'centered-vertically
                                   'bottom-resizeable
                                   'top-resizeable
                                   'right-resizeable
                                   'left],
                         :loadable (shadow.lazy/loadable
                                    [pinkgorilla.layout.spaces/bottom
                                     pinkgorilla.layout.spaces/left-resizeable
                                     pinkgorilla.layout.spaces/description
                                     pinkgorilla.layout.spaces/fill
                                     pinkgorilla.layout.spaces/right
                                     pinkgorilla.layout.spaces/viewport
                                     pinkgorilla.layout.spaces/top
                                     pinkgorilla.layout.spaces/centered-vertically
                                     pinkgorilla.layout.spaces/bottom-resizeable
                                     pinkgorilla.layout.spaces/top-resizeable
                                     pinkgorilla.layout.spaces/right-resizeable
                                     pinkgorilla.layout.spaces/left])}},
   "ui-rnd" {'ui.rnd {:sci-def ['rnd], :loadable (shadow.lazy/loadable [pinkgorilla.layout.rnd/rnd])}},
   "ui-popover" {'ui.popover {:sci-def ['popover 'tooltip],
                              :loadable (shadow.lazy/loadable
                                         [pinkgorilla.layout.popover/popover pinkgorilla.layout.popover/tooltip])}},
   "ui-gridlayout" {'ui.gridlayout {:sci-def ['gridlayout],
                                    :loadable (shadow.lazy/loadable [pinkgorilla.layout.gridlayout/gridlayout])}}})
(def sci-lazy-ns-dict
  {'tick.core "tick",
   'ui.rnd "ui-rnd",
   'ui.gridlayout "ui-gridlayout",
   'input2 "ui-ionslider",
   'site "ui-site",
   'ui.popover "ui-popover",
   'cljs.pprint "cljs-pprint-frisk",
   'goldly.js "ui-repl",
   'goldly.log "ui-repl",
   'http "ui-repl",
   'tick.goldly "tick",
   'input "ui-input",
   'spaces "ui-spaces",
   'layout "ui-site",
   'ui.frisk "cljs-pprint-frisk",
   'ui.codemirror "ui-codemirror",
   'cm "ui-codemirror"})
